stages:
  train:
    cmd: python ../benchmark.py
    deps:
    - ../benchmark.py
    - ../../src/
    params:
    - data
    - train
    - dimm
    outs:
    - benchmarks.csv
    plots:
    - results.csv
