stages:
  host_name:
    cmd: ../get_hostname.sh
    outs:
    - hostname.yaml:
        cache: false
    always_changed: true
  simple_train:
    vars:
    - exp_name: simple
    cmd: python ../benchmark.py --exp_name ${exp_name}
    deps:
    - ../benchmark.py
    - ../../src/
    params:
    - ${exp_name}.yaml:
      - data
      - train
      - dimm
    - hostname.yaml:
      - name
    outs:
    - ${exp_name}_benchmarks.csv:
        cache: false
    metrics:
    - ${exp_name}_metrics.json:
        cache: false
    plots:
    - ${exp_name}_plots.csv:
        cache: false
        title: CPU Times
        x: dimm_n_dpu
        y: cpu_train_times
    - ${exp_name}_plots.csv:
        cache: false
        title: DPU Times
        x: dimm_n_dpu
        y: dpu_train_times