[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.7.1",
    "cmake>=3.21",
    "scikit-build>=0.12",
    "ninja",
    "pkgconfig",
    "setuptools_scm>=6.2",
]

build-backend = "setuptools.build_meta"
