stages:
  host_name:
    cmd: ../get_hostname.sh
    outs:
    - hostname.yaml:
        cache: false
    always_changed: true
  download:
    wdir: data
    cmd: wget https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz
    deps:
    - https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz
    outs:
    - HIGGS.csv.gz
  unzip:
    wdir: data
    cmd: gunzip -k HIGGS.csv.gz
    deps:
    - HIGGS.csv.gz
    outs:
    - HIGGS.csv:
        cache: false
  serialize:
    wdir: data
    cmd: python convert_to_pq.py
    deps:
    - HIGGS.csv
    outs:
    - higgs.pq:
        cache: false
  higgs_small:
    cmd: python ../benchmark.py
    deps:
    - ../benchmark.py
    - ../../src/
    - data/higgs.pq
    params:
    - params_small.yaml:
      - data
      - train
      - dimm
    - hostname.yaml:
      - name
    outs:
    - benchmarks.csv:
        cache: false
    metrics:
    - metrics.json:
        cache: false
    plots:
    - results.csv:
        cache: false
  higgs_big:
    cmd: python ../benchmark.py
    deps:
    - ../benchmark.py
    - ../../src/
    - data/higgs.pq
    params:
    - params_big.yaml:
      - data
      - train
      - dimm
    - hostname.yaml:
      - name
    outs:
    - benchmarks.csv:
        cache: false
    metrics:
    - metrics.json:
        cache: false
    plots:
    - results.csv:
        cache: false
