stages:
  log:
    cmd: python ../machine_log.py
    outs:
    - dpu_diag.txt:
        cache: true
    - machine.yaml:
        cache: false
    always_changed: true
  download:
    wdir: data
    cmd: wget https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz
    deps:
    - https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz
    outs:
    - HIGGS.csv.gz
  unzip:
    wdir: data
    cmd: gunzip -k HIGGS.csv.gz
    deps:
    - HIGGS.csv.gz
    outs:
    - HIGGS.csv:
        cache: false
  serialize:
    wdir: data
    cmd: python convert_to_pq.py
    deps:
    - HIGGS.csv
    outs:
    - higgs.pq:
        cache: false
  train:
    cmd: python ../benchmark.py
    deps:
    - ../benchmark.py
    - ../../src/
    - data/higgs.pq
    params:
    - data
    - train
    - dimm
    - machine.yaml:
      - hostname
      - nr_dpus
      - frequency
    outs:
    - benchmarks.csv:
        cache: false
    metrics:
    - metrics.json:
        cache: false
    plots:
    - plots.csv:
        template: multiline.json
        cache: false
        title: Train Times
        x: dimm_n_dpu
        y: cpu_train_times
