package:
  name: dpu_kmeans
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"

  host:
    - python
    - pip
    - pybind11 >=2.6.0
    - scikit-build
    - cmake >=3.18
    - ninja

  run:
    - python


test:
  imports:
    - dpu_kmeans
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  summary: A project to use DPUs for tree algorithms.
  license_file: LICENSE
