data:
  synthetic: true
  n_points: 4096.e+3
  n_dim:
    - 16
    - 4
  centers: 16
  random_state: 42
train:
  n_init: 10
  max_iter: 500
  tol: 1.e-4
  n_clusters: 16
  random_state: 42
dimm:
  n_dpu: 512
